"use client";

import React from "react";
import EmployeesTable from "./employeesTable";
// import type { Metadata, Viewport } from "next";

// export const metadata: Metadata = {
//   title: "ข้อมูลลูกค้า",
//   description: "Generated by JaypingDev",
// };

function User() {
  return (
    <div className="flex-1 p-4 ">
      <h1 className="text-xl lg:text-2xl font-bold ">ข้อมูลลูกค้า</h1>
      <div>
        <EmployeesTable />
      </div>
    </div>
  );
}

export default User;
