"use client";
import StatusFilter from "@/components/ui/Filter";
import Status from "@/components/ui/Status";
// import TabbarSection from "../containers/sandbox-page/tabbar-section";
import TableSection from "../containers/home-page/table-section";

import React from "react";

// Metadata
// export const metadata = {
//   title: "Sportswear Shop",
//   description: "Generated by JaypingDev",
// };

function Dashboard() {
  return (
    <div className="flex-1 p-4">
      <h1 className="text-xl lg:text-2xl font-bold ">Dashboard</h1>
      {/* <Status /> */}
      {/* <StatusFilter /> */}
      <div>
        <TableSection />
      </div>
    </div>
  );
}

export default Dashboard;
